name: flutter_gokwik
description: A new flutter plugin project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_spinkit: "^4.1.2"
  upi_pay: ^0.2.0
  http: ^0.12.1
  otp_text_field: ^1.0.2
  sms_otp_auto_verify: ^1.2.2
  eventify: ^0.1.4


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_gokwik
        pluginClass: FlutterGokwikPlugin
      ios:
        pluginClass: FlutterGokwikPlugin

  # To add assets to your plugin package, add an assets section, like this:
  assets:
    - assets/images/
    # - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
